### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by Andrei-Fogoros** [yiiext/webshell-module#7]
Hello @cebe, @samdark,
Please tell us what is the license of this repository?

Thanks in advance! :)

**Comment by Andrei-Fogoros** [comment]
> It was not specified back then. What do you have in mind? I can make it BSD same as Yii's license.

Thank you for your response. I would greatly appreciate it if you could change the license to BSD-3-Clause. Thank you!

**Comment by samdark** [comment]
Done.
